name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Deploy to server
        run: |
          scp -r ./dist i308181@${{ secrets.SERVER_IP }}:/home/i308181/lasociedadelmeme/backend/backend_memes
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} i308181@${{ secrets.SERVER_IP }} 'cd /home/i308181/lasociedadelmeme/backend/backend_memes && npm install && npm run dev'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}

